/**
 * Pattern-orchestrator tools (device-neutral, dispatch by `port`).
 *
 *   - apply_pattern       , realize a drum/melodic pattern on a target via
 *                            its declared realizer (live_stream today; the
 *                            mode is gated by the device, not the schema).
 *   - list_pattern_recipes, read the named pattern library; with a port,
 *                            also report what that target supports.
 *   - import_songsterr    , fetch a part of a Songsterr tab (read-only, no
 *                            device) → the part roster / sections / tempo, and
 *                            per-section voice grids to feed apply_pattern.
 *                            Selection reaches ANY part, and BOTH kinds
 *                            convert: a drum part to GM-percussion char grids,
 *                            a melodic part to one mini-notation pitch row
 *                            (with per-cell velocity, note length and tie).
 *
 * One verb + one lister, shared across every pattern target (Circuit Tracks,
 * SPD-SX, and any voice device with a voice_map), adding a sequencer is a
 * descriptor (pattern_realizers + voice_map), not a new tool.
 */

import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import * as z from 'zod/v4';

import { executeApplyPattern, executeListPatternRecipes } from '../dispatcher/patterns.js';
import { executeImportSongsterr } from '../dispatcher/songsterr.js';
import { PACK_DESC, PORT_DESC, asError, asText } from './shared.js';

export function registerPatternTools(server: McpServer): void {
  server.registerTool('apply_pattern', {
    title: 'Apply Pattern',
    // destructiveHint reflects the WORST-CASE mode: ncs_upload persists + overwrites
    // a flash slot (gated by confirm_overwrite + backup_first, same act as upload_project).
    // live_stream / record_capture are reversible.
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true },
    description: [
      'Realize a drum / step pattern on a sequencer target (Circuit Tracks drums, Roland SPD-SX, or any voice device with a voice_map).',
      'Pattern source (pick one): `recipe` (named library id, see list_pattern_recipes), `voices` (map voice to step string, e.g. {kick:"x...x...", snare:"....x..."}), `notation` (comma-stack mini-notation "bd*4, hh*8, ~ sd ~ sd", needs `steps`), or an imported `tab` / `midi_file`.',
      'Step strings: char grid "x...x..." (X = accent), mini-notation "bd ~ ~ ~" (rest ~, repeat *n, subgroup [], stack ,, suffixes :len / @vel / _), or Euclidean "E(k,n)" / "E(k,n,rot)" (e.g. E(5,16) spreads 5 hits over 16).',
      'Micro-step rolls: char-grid digits 1-6 = that many evenly-spaced sub-hits inside one step (6 = the trap hi-hat "buzz"). Imported off-grid onsets (32nds, triplets, swing) auto-place on micro-ticks with true timing on every route.',
      'Melodic voices carry pitch with note tokens: "c2 ~ g2 ~" (bassline), "c3+eb3+g3 ~ ~ ~" (chord, join with +), "c3 eb3 g3 c4" (arp). Scientific pitch, middle C = c4 = 60, # / s = sharp, b = flat; `key` / `transpose` move authored pitches to another key.',
      'SUFFIXES on a hit token, any order: ":" a LENGTH in steps ("c3:4" holds four steps, "c3:1/6" is staccato; range 1/6 to 16), "_" a TIE forward into the next onset ("c3:16_", or bare "c3_" to compute the length), "@" a VELOCITY 1..127 ("c3@110", combined "c3:4@110_", one set per chord token). Default: one step, untied, accent-table velocity. Author pads and drones with a length rather than the target synth\'s envelope, which vanishes when the synth is swapped; a char grid has nowhere to put a suffix, and its "X" accent is one bit, not a dynamic ladder.',
      'mode live_stream (default) auditions live (nothing stored); record_capture streams while the device records into a pattern; ncs_upload (Circuit Tracks) writes the pattern as a stored project that persists and replays on the device (needs ncs_slot + ncs_template, an exported .ncs).',
      'EXTERNAL gear (ncs_upload): external_targets sequences another device off the host\'s MIDI tracks. Working SPD-SX call: [{device:"spd-sx", track:"midi2", note_offset:12}] puts the drum voices on Circuit MIDI 2 via the SPD-SX note map (see external_targets and note_offset for the octave shift and the internal-drums option).',
      'WHOLE SONG (ncs_upload): the `arrangement` input authors a multi-section song into one auto-advancing project. Author the sections yourself, or paste grids from import_songsterr whole_song (same shape); see `arrangement` for the 8 x 32-step capacity ceiling.',
      'Voices resolve to pads/tracks via the target voice_map. A drum voice the target lacks FOLDS to its nearest musical substitute (china to crash, conga to tom) and is reported; a voice with no substitute errors. Confirm by ear (no readback).',
      'Mapping a big groove onto a small kit is lossy: the receipt reports PIECE COMPRESSION (re-voiced pieces with hit counts, merged pieces), and nothing when the mapping is clean. Before a persisting write, pre-flight with dry_run:true and relay real compression to the user (see dry_run).',
    ].join(' '),
    inputSchema: {
      port: z.string().describe(PORT_DESC),
      recipe: z.string().optional().describe('Named library recipe id (e.g. "four_on_the_floor"). The MELODIC recipes (minor_triad, major_triad, octave_bass, minor_arp_up, lead_hook) are written in C: set `key` ("G", "Eb", "F#") or `transpose` to play one in another key. Mutually exclusive with voices / notation.'),
      voices: z.record(z.string(), z.string()).optional().describe('Inline per-voice map: voice name → char-grid or mini-notation line. Names resolve through the target voice_map (list_pattern_recipes with a port lists what it can place); on Circuit Tracks the "hat" voice is Drum 3, so name the "drum4" voice to put a hi-hat roll on Drum 4 instead.'),
      notation: z.string().optional().describe('Inline comma-stack mini-notation. Requires `steps`.'),
      tab: z.string().optional().describe('ASCII drum tablature (community text format). One line per drum voice with a label then step chars: "HH|x-x-x-x-|", "SD|----o---|", "BD|o---o---|". Labels map to voices (BD/B/K=kick, SD/S=snare, HH/H=hat, OH=openhat, CC/C=crash, RD/R=ride, T/FT=tom, RS=perc). Chars: x/o=hit, X/O=accent, -/./space=rest, g=ghost, b=buzz roll (the only verified Circuit micro-roll). Bars split on "|"; blank-line-separated systems concatenate in order (so a multi-bar song section works). Step count = the column count; the Circuit caps at 32. Mutually exclusive with recipe/voices/notation.'),
      midi_file: z.string().optional().describe('Path to a Standard MIDI File (.mid) on disk. Imports its drum track (MIDI channel 10, General-MIDI percussion → kick/snare/hat/openhat/crash/ride/tom/perc, full GM 35-81) and quantizes to a 16th-note grid; add `midi_tracks` to ALSO import melodic channels (bass/chords/lead) as pitched voices. The free, reliable "play any song" source (download a free .mid). Use midi_from_bar / midi_bars to pick a section (defaults to bars 1-2 = 32 steps; 4/4 assumed). Velocity >=100 → accent, <=40 → ghost. Mutually exclusive with the other pattern sources.'),
      midi_from_bar: z.number().int().min(1).optional().describe('midi_file only: 1-based bar to start importing from (assumes 4/4). Default 1.'),
      midi_bars: z.number().int().min(1).max(8).optional().describe('midi_file only: number of bars to import (assumes 4/4). Default 2 (= 32 sixteenth-note steps, the Circuit pattern max).'),
      midi_channel: z.number().int().min(1).max(16).optional().describe('midi_file only: 1-based MIDI channel holding the drums. Default 10 (the GM convention). Drum-library groove packs often sequence on another channel (the Mixwave Sleep Token II pack uses 16); the no-notes warning lists the channels present.'),
      drum_map: z.union([z.string(), z.record(z.string(), z.union([z.string(), z.number()]))]).optional().describe('midi_file only: percussion remap for non-GM key maps. Note number (string key) to a voice name ("clap") or GM number (39), OR a named preset string: "mixwave-st2-grooves" (the Mixwave Sleep Token II groove pack, ch16). Warnings name any unmapped numbers with hit counts, which is exactly what this map needs to cover.'),
      midi_tracks: z.record(z.string(), z.number().int().min(1).max(16)).optional().describe('midi_file only: ALSO import MELODIC channels as pitched voices, a map of voice name to 1-based MIDI channel, e.g. {"bass": 3, "chord": 2}. Voices route via the target voice_map (bass=Synth1, lead=Synth2 on the Circuit). Chords group per step (max 6 notes). Not sure which channel? Run once without it: the receipt lists every channel with note counts, pitch range, and a chords flag (lowest range = usually the bass).'),
      steps: z.number().int().min(1).max(64).optional().describe('Grid resolution per bar (8/16/32). Required for notation; optional for char-grid voices (inferred from length).'),
      bpm: z.number().min(20).max(300).optional().describe('Tempo in BPM. Default 120 for the live audition. For ncs_upload this is ALSO the tempo STORED in the project, so pass the song\'s real tempo: a stored project carries its own tempo and the device plays it at that speed when loaded. Omit it and the project keeps whatever the ncs_template was set to (the receipt says so). When importing a song, import_songsterr already returns its bpm; pass that through rather than asking the user to state it twice.'),
      mode: z.enum(['live_stream', 'record_capture', 'ncs_upload']).optional().describe('Realizer mode. Default = the target\'s first advertised realizer.'),
      repeat: z.number().int().min(1).max(64).optional().describe('Loop count. Clamped to a ~30s total realize budget.'),
      armed: z.boolean().optional().describe('record_capture only: pass true after Record is armed on the device to stream the take.'),
      ncs_template: z.string().optional().describe('ncs_upload only: path to an exported .ncs project to template-modify (the device cannot author one from scratch).'),
      ncs_slot: z.number().int().min(1).max(64).optional().describe('ncs_upload only: target PROJECT 1..64, numbered exactly as the device shows it (Project 35 = 35). OVERWRITE GATE: this OVERWRITES that slot, so the tool reads it first. An EMPTY slot writes through; an OCCUPIED slot REFUSES and names the project it would replace. Pass confirm_overwrite:true (only on user save/overwrite authorization) to overwrite an occupied slot.'),
      ncs_tempo: z.number().int().min(40).max(240).optional().describe('ncs_upload only: the tempo to STORE in the project, 40..240 BPM (the device\'s range, whole numbers only). Rarely needed: `bpm` is stored automatically, so pass this only when the stored tempo should deliberately differ from the audition tempo. Out of range REFUSES rather than clamping, because a project silently stored at the wrong speed is the failure this exists to prevent.'),
      colour: z.union([z.number().int(), z.string()]).optional().describe('ncs_upload only: the COLOUR the device lights this project\'s pad with in Projects View, which is how a player finds the song mid-set (that view shows a grid of lit pads, not names). A palette name (case-insensitive) or its index 0..13. Most-separable first, so several songs stay tellable apart at a distance: Red > Cyan > Purple > Green > Yellow > Orange > Pink > Blue. Omitted keeps the template\'s colour and the receipt says so; Blue is the untouched default, so a Blue pad reads as "never stamped". An unknown colour REFUSES rather than substituting one.'),
      color: z.union([z.number().int(), z.string()]).optional().describe('Alias for `colour`, same argument. Pass either spelling; passing both with different values refuses.'),
      pack: z.number().int().min(1).max(32).optional().describe(`ncs_upload only: which pack to write to. The overwrite gate, the pre-write backup, and the write all target it together. Load this pack's samples first (upload_sample/upload_kit pack:N), or \`drum_binding\` slots resolve against a different pool. ${PACK_DESC}`),
      key: z.string().optional().describe('Target key root (C, G, Eb, F#…) for melodic content. Transposes the C-based pitches up to that root. Ignored if `transpose` is set; drum triggers are unaffected.'),
      transpose: z.number().int().min(-48).max(48).optional().describe('Semitone shift for authored pitches (e.g. +7, -5). Takes precedence over `key`. Drum/un-pitched hits are not transposed.'),
      scale: z.string().optional().describe('ncs_upload only: the musical scale the Circuit constrains the pattern to (e.g. "C minor", "G mixolydian", "dorian", "chromatic"). The device re-quantizes notes to its scale on playback. DEFAULT = Chromatic, so authored absolute pitches play LITERALLY (use this for exact transcriptions). Set a scale to keep the pattern in-key and let the on-device Scale knob remap it musically.'),
      round_robin: z.record(z.string(), z.array(z.string())).optional().describe('Spread a voice\'s consecutive hits across 2+ drum tracks so a fast RINGING sound (hats / ride / cymbal) overlaps and bleeds instead of choking itself. Each Circuit drum track is monophonic: a new hit cuts the previous one on that SAME track, which sounds abruptly cut off. Map a source voice to the target drum tracks to rotate across, e.g. {"hat":["drum3","drum4"]} deals hit 1->drum3, hit 2->drum4, hit 3->drum3, … Load the SAME sample on each target track so it sounds like one instrument ringing. Works in live_stream (audition) and ncs_upload. The source voice is consumed; its hits now live on the targets.'),
      drum_flips: z.record(z.string(), z.record(z.string(), z.number().int().min(0).max(63))).optional().describe('ncs_upload only: per-step SAMPLE FLIPS (the Circuit\'s feature for playing a different sample on individual steps of a drum track). Map a drum track ("drum1".."drum4") to { 1-based step number → absolute sample slot 0..63 }, e.g. {"drum1":{"9":2,"13":15}} makes Drum 1 step 9 play sample slot 2 and step 13 play slot 15, while its other hits play the track\'s default sample. This is how MULTIPLE drum pieces (kick + snare + sticks) share ONE track: the default sample on most steps, flips on the rest. The step must already be a hit (authored by a voice); flipping a rest does nothing. Slot is the wire slot = the device\'s "Sample N" minus 1 (Sample 3 = slot 2).'),
      drum_binding: z.array(z.number().int().min(0).max(63)).length(4).optional().describe('ncs_upload only: point each of the 4 drum tracks (Drum1..Drum4, in order) at a specific kit sample slot 0..63, so the project loads TURNKEY with drums already pointing at the right kit pieces (no on-device hand-assignment). Exactly 4 slots, e.g. [0,7,2,11] puts Drum1=slot0(kick), Drum2=slot7(crash), Drum3=slot2(closed_hat), Drum4=slot11(china). Default (omitted) is the canonical stoken layout kick/snare/closed_hat/ride on slots [0,1,2,3]. Slot is the wire slot = the device\'s "Sample N" minus 1 (Sample 12 = slot 11). Project-global: applies whether authoring a single pattern or a multi-section `arrangement`. COMPOSES with condense_drums (bind first, condense onto the bound layout): the binding then declares that each track\'s OWN role sample (Drum1=kick, Drum2=snare, Drum3=closed hat, Drum4=ride) lives at the slot you name, condensation lays the groove onto those tracks, and its per-step sample flips resolve against YOUR slots, not the canonical layout. A folded piece outside those four roles (crash, tom) cannot be located in a custom pool, so its flip is skipped with a warning and the hit keeps the track\'s bound sound; keep such a piece distinct via drum_flips with its real pool slot.'),
      condense_drums: z.boolean().optional().describe('ncs_upload only: ALSO lay the drum part down, CONDENSED, on the Circuit\'s own four drum tracks, stored SILENT (mixer level 0). For the normal external-kit setup, where external_targets sends the real drums to an SPD-SX on MIDI 2 and the Circuit\'s drum tracks would otherwise sit empty: the same groove is squeezed onto Drum 1..4 (kick / snare / closed hat / ride), per-step contention resolved by fold distance then velocity, and folded pieces (crash, tom, ride bell) keep their identity via per-step SAMPLE FLIPS back to their own sample. Nothing is audible until the user raises a drum track on the mixer, so it costs nothing and gives them internal drums to blend in live. COMPOSES with drum_binding: bind first, condense onto the bound tracks, flips resolved against the bound slots (see drum_binding for the rule). Conflicts only with external_targets.also_internal (the raw voices and the condensed copy would claim the same tracks) and refuses that rather than guessing. Works per-section inside `arrangement`.'),
      project_name: z.string().optional().describe('ncs_upload only: the PROJECT NAME stored in the file, the name the device\'s pack directory and Components show, up to 32 ASCII characters (letters, digits, punctuation, spaces), space-padded into the fixed 32-character field. Omitted keeps the template\'s name byte-identical and the receipt says so, which is how every project authored from one template ends up listed under the template\'s name; pass the song part\'s real name ("MySong Verse") so the card stays navigable. Longer than 32 or non-ASCII REFUSES rather than truncating silently: a shortened name is how two different songs end up reading identically. No alias; the argument is exactly `project_name`.'),
      mixer_levels: z.strictObject({
        synth1: z.number().int().optional().describe('Synth 1 stored level 0..127.'),
        synth2: z.number().int().optional().describe('Synth 2 stored level 0..127.'),
        drum1: z.number().int().optional().describe('Drum 1 stored level 0..127.'),
        drum2: z.number().int().optional().describe('Drum 2 stored level 0..127.'),
        drum3: z.number().int().optional().describe('Drum 3 stored level 0..127.'),
        drum4: z.number().int().optional().describe('Drum 4 stored level 0..127.'),
      }).optional().describe('ncs_upload only: STORED per-track mixer levels, written into the project so they survive loading (a live mixer CC does not; loading a project overwrites it). Raw 0..127, the same numbers as the mixer CCs; the factory default is 100. DEFAULT: both SYNTHS store level 0 when not named here (stored-silent, the repertoire convention: external gear carries the synth voices, raised on the mixer by hand when wanted). Name synth1/synth2 to override, including deliberately loud values, e.g. {"synth1":100}. Unnamed DRUMS keep the template\'s stored level; a drum key overrides condense_drums\' stored 0 for that track. The receipt lists every track\'s outcome. Out of range REFUSES rather than clamping. A Save done on the device recaptures the physical faders, so re-apply after any manual save.'),
      preserve_template_gates: z.boolean().optional().describe('ncs_upload only: keep the NOTE LENGTHS and TIE-FORWARD flags the ncs_template already holds, instead of resetting every re-authored note to a one-step gate. Default true, and leave it that way. Authoring could not write note lengths until recently, so any long or tied note in a stored project was dialled in BY HAND on the device in Gate View, and flattening it turns a held pad or drone into a blip with nothing in the diff to show it. A note whose own step states a length (the "c3:4" suffix) uses that; the template only fills in the rest. Pass false only when the user explicitly wants the template\'s hand-set lengths discarded.'),
      confirm_overwrite: z.boolean().optional().describe('ncs_upload only: overwrite gate. Omitted/false reads the target slot first and refuses only if it is occupied. Pass true to overwrite an occupied slot (skips the read), only when the user authorized it.'),
      backup_first: z.boolean().optional().describe('ncs_upload only: backup-before-overwrite. Default true: when confirm_overwrite overwrites an occupied slot, save its current project to a .ncs backup (~/mcp-midi-backups) first so the change is reversible. Pass false to skip the pre-write backup read.'),
      dry_run: z.boolean().optional().describe('Pre-flight: resolve + compile + (ncs_upload) author + fit-check, sending NOTHING to the device (no reads, no gate, no backup, no transfer). Returns status "dry_run" with the full receipt: the piece-compression report (re-voiced pieces with hit counts, e.g. "ride (64 hits) to hat"; merged pieces whose distinct voices are lost), arrangement layout, and warnings. When the report shows merges or high-hit-count re-voicings, TELL THE USER what will be compressed and offer alternatives (route drums to a bigger target via external_targets, keep pieces distinct on one track via drum_flips, or accept), then re-call without dry_run.'),
      external_targets: z.array(z.object({
        device: z.string().describe('External device port (id or name), e.g. "spd-sx".'),
        track: z.string().optional().describe('Host outward MIDI track ("midi1"/"midi2"). Defaults from the rig links (the rig manifest when configured, else MCP_RIG_LINKS; see describe_rig).'),
        voices: z.array(z.string()).optional().describe('Voices to route externally. Defaults to every pattern voice the external device can place.'),
        also_internal: z.boolean().optional().describe('false (default) = the voices play ONLY on the external device (e.g. "beat on MIDI 2" goes to the SPD-SX alone). true = also play them on the Circuit\'s own drums AND the external device ("on the drum tracks and MIDI 2"), the same beat on both at once.'),
        note_offset: z.number().int().min(-48).max(48).optional().describe('Semitones added to the externally-routed notes (clamped 0..127). The Circuit Tracks transmits MIDI-track notes ONE OCTAVE BELOW the authored value (confirmed by USB capture), so pass note_offset:12 so the notes land on the external device\'s pad notes. Default 0 (no shift).'),
        voice_notes: z.record(z.string(), z.number().int().min(0).max(127)).optional().describe('Per-voice PAD PINNING: route a voice to an explicit note on the external device, bypassing its voice_map and the fold layer. The idle-pad recovery: when the compression report shows a fold (busy_hat onto the hat pad) AND the kit has an unused pad, load the right sample there and pin the voice, e.g. {"busy_hat": 39, "ride_bell": 49} keeps both pieces distinct on an SPD-SX whose clap/crash pads are idle for this song. note_offset still applies; the pinned voice needs no voice_map entry.'),
      })).optional().describe('ncs_upload only: route some/all voices to an EXTERNAL device sequenced via the host\'s MIDI 1/2 tracks (Circuit Tracks to e.g. a Roland SPD-SX). Those voices author onto the host MIDI track using the external device\'s note map; the external device must receive on that track\'s channel. Default plays the voices ONLY on the external device; also_internal:true also plays them on the Circuit\'s internal drums. Verify the host\'s actual transmit channel + octave with `npm run capture-midi` (the Circuit can send MIDI-track notes an octave low: use note_offset).'),
      arrangement: z.object({
        sections: z.array(z.object({
          name: z.string().describe('Section name ("Intro", "Verse", "Chorus"), shown in the receipt and on-device layout.'),
          recipe: z.string().optional().describe('Named library recipe id for this section.'),
          voices: z.record(z.string(), z.string()).optional().describe('Per-voice char-grid / mini-notation map for this section (the agent-authored form).'),
          notation: z.string().optional().describe('Comma-stack mini-notation for this section. Requires `steps`.'),
          tab: z.string().optional().describe('ASCII drum tab for this section.'),
          steps: z.number().int().min(1).max(64).optional().describe('Grid resolution for this section\'s inline forms.'),
          repeat: z.number().int().min(1).max(16).optional().describe('Consecutive plays of this section (default 1). "Verse ×2" = repeat:2.'),
        })).min(1).describe('The song\'s sections. Without `order`: played in listed order, each `repeat` times. Each uses exactly one of recipe / voices / notation / tab.'),
        order: z.array(z.string()).optional().describe('Play order as section NAMES, revisits allowed: ["Verse","Chorus","Verse","Chorus"]. Overrides listed order + per-section repeat.'),
        scene_plan: z.array(z.array(z.string()).min(1)).min(1).optional().describe('Explicit SCENE grouping, when the automatic layout\'s greedy merge cannot express the split you want: each inner list is one scene\'s sections by NAME, e.g. [["Fill"],["A","B","C"],["D","E"],["F","G"]] = a 1+3+2+2 chain of 4 scenes. The plan IS the play order (scenes play 1..N, then loop), so it is mutually exclusive with `order` and ignores per-section repeat. A scene\'s members must be adjacent in `sections` (a scene stores one contiguous pattern range); a section may recur across scenes (repeats cost no pattern slots, e.g. three scenes pointing at one ostinato) but only once within a scene; every section must land in some scene; max 4 scenes (the device-confirmed range). Unknown names, double placement, unplaced sections and >4 scenes REFUSE with the fault named.'),
      }).optional().describe('ncs_upload only: author a MULTI-SECTION song (mutually exclusive with the single-pattern sources). Sections land in pattern slots and auto-advance via the pattern chain (≤8 plays incl. repeats; hardware-confirmed) or a scene-chain (≤4 scene steps; community-beta), chosen automatically, or grouped exactly as you say with scene_plan; the song loops. CEILING: 8 pattern slots x 32 steps = 256 steps per track = 16 bars at a 16th grid in 4/4. That is one project; a longer song needs several, chopped on its section markers (import_songsterr whole_song + parts). Author the sections yourself, or paste grids from import_songsterr (whole_song mode returns this exact shape).'),
    },
  }, async ({
    port, recipe, voices, notation, tab, midi_file, midi_from_bar, midi_bars, midi_channel, drum_map, midi_tracks, steps, bpm,
    mode, repeat, armed, ncs_template, ncs_slot, ncs_tempo, colour, color, project_name, mixer_levels, pack, key, transpose, scale, round_robin, drum_flips, drum_binding,
    condense_drums, preserve_template_gates, confirm_overwrite, backup_first, dry_run, external_targets, arrangement,
  }) => {
    try {
      const result = await executeApplyPattern({
        port, recipe, voices, notation, tab, midi_file, midi_from_bar, midi_bars, midi_channel, drum_map, midi_tracks, steps,
        bpm,
        mode, repeat, armed, ncs_template, ncs_slot, ncs_tempo, colour, color, project_name, mixer_levels, pack, key, transpose, scale, round_robin, drum_flips, drum_binding, condense_drums, preserve_template_gates, confirm_overwrite, backup_first, dry_run, external_targets, arrangement,
      });
      return asText(result);
    } catch (err) {
      return asError(err);
    }
  });

  server.registerTool('list_pattern_recipes', {
    title: 'List Pattern Recipes',
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    description: [
      'List the named drum-pattern library (four_on_the_floor, boom_bap, half_time, two_step, amen, trap_hats, …) for use with apply_pattern.',
      'Pass `port` to also see what that target supports: its realizer modes and the abstract voices its voice_map can place.',
    ].join(' '),
    inputSchema: {
      port: z.string().optional().describe(PORT_DESC),
    },
  }, async ({ port }) => {
    try {
      return asText(executeListPatternRecipes({ port }));
    } catch (err) {
      return asError(err);
    }
  });

  server.registerTool('import_songsterr', {
    title: 'Import Song',
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    description: [
      'Fetch a part of a song from Songsterr, ready for apply_pattern. Read-only: public tab data, nothing is sent to a device.',
      'NOT DRUM-ONLY: it fetches ANY part on the tab (drums, bass, guitars, keys, vocal line), and drums are only the DEFAULT when you name none. Select one with list_tracks / `track` / `track_name`.',
      'BOTH kinds convert. A DRUM part reads notes as GM PERCUSSION and returns a char grid per voice. A MELODIC part converts string+fret against the part\'s own tuning (pitch = tuning[string] + fret) into ONE mini-notation pitch row ("d#3:4@110 ~ ~ d4:1/2@85", chords +-joined).',
      'That row CARRIES NOTE LENGTH (":len" in steps), VELOCITY ("@vel") and TIE ("_"), so pasting it into apply_pattern holds a pad instead of landing a one-step blip. A note past the 16-step gate ceiling auto-splits into a tied chain.',
      'ARTICULATIONS (palm mute, accent, let-ring, hammer-on / slide) become real gate + velocity: SHORT AND OVERLAPPING GATES ARE THE ARTICULATION, do not normalise them. See `articulations` to tune.',
      'REPORTS WHAT IT DROPS: `dropped_fidelity` separates what is NEVER READ (`not_parsed`: bends, vibrato) from what was read but not authored (`parsed_not_authored`: a slide with no written destination). Relay the second to the user.',
      'Flow: `url` or `query` first returns the parts, SECTIONS and TEMPO map; call again with a window (`section`, or `from_measure`/`to_measure`) for the step grids (`voices`) and that window\'s LOCAL tempo, which apply_pattern takes as `bpm`.',
      'whole_song:true plans the WHOLE song: `song_plan` chops on the source\'s markers, shared by all `parts`; `arrangement` = the deduped bank, keyed over EVERY selected part (ceiling 8 patterns x 32 steps = 16 bars in 4/4 per project).',
      'Drum voices are GM (kick/snare/hat/openhat/crash/ride/tom/perc); non-GM numbers are skipped and NAMED in warnings, re-import with `drum_map`.',
    ].join(' '),
    inputSchema: {
      url: z.string().optional().describe('Songsterr tab URL (…-s1467797t11) or bare id (1467797 / 1467797t11). The t-selector picks the part. Provide this OR `query`.'),
      query: z.string().optional().describe('Song name to search ("Sleep Token Gethsemane") when you don\'t have the URL. Resolves to the best Songsterr match; alternatives are returned.'),
      list_tracks: z.boolean().optional().describe('DRY RUN: list every part the song has (drums, bass, guitars, keys, vocal line) and stop. One metadata read: no part is downloaded, no track is selected, nothing is authored. Returns mode:"list_tracks" with tracks[] ({partId, name, instrument, is_drums}), the drum subset, and a note on what converts to grids. Use it to answer "what parts does this song have?" and to pick a `track`. Works on a song with NO drum part, which the default path refuses. Mutually exclusive with whole_song and the window args.'),
      track: z.number().int().min(0).optional().describe('Part override, ANY instrument: pass the `partId` from list_tracks / all_tracks / drum_tracks (a meta-track index, NOT its position in the list). This is how a bass, organ or piano part is selected.'),
      track_name: z.string().optional().describe('Pick the part by name/instrument substring, matched against EVERY part, not just the drum ones ("Programmed", "II", "electronic", "bass", "organ").'),
      section: z.string().optional().describe('Window by section name ("Bridge", "Chorus"). Case-insensitive; if a name repeats, the first is used.'),
      from_measure: z.number().int().min(1).optional().describe('Window start at this DISPLAYED measure number (1-based, matching the tab UI). Prefer this or `section` over from_beat.'),
      to_measure: z.number().int().min(1).optional().describe('Window end at this displayed measure number (inclusive).'),
      from_beat: z.number().min(0).optional().describe('Advanced: window start as a raw quarter-beat offset. Use only for sub-measure windows; `from_measure` overrides it if both are given.'),
      beats: z.number().min(1).optional().describe('Advanced: window length in quarter-beats.'),
      steps: z.number().int().optional().describe('Grid resolution as steps-PER-BEAT: 4 = 16ths (default), 8 = 32nds. (Note: this is per-beat, unlike apply_pattern\'s `steps` which is per-bar; it is not carried into apply_pattern, which infers length from the returned grids.)'),
      whole_song: z.boolean().optional().describe('Plan the WHOLE song. On a DRUM part: a deduped section bank + play order, as `arrangement` (paste into apply_pattern); `fuzz` merges near-identical grooves to fit the 8 pattern slots. On a MELODIC part, or with `parts`: `song_plan`, a project layout cut on the source\'s own SECTION MARKERS, respecting the 8x32 = 256-step (16-bar) ceiling, plus `arrangement` when drums are among the parts, keyed over EVERY selected part. Pattern boundaries land on BAR LINES, packed from each bar\'s own time signature, so a metre-changing song returns `pattern_steps`, the per-pattern step counts. Mutually exclusive with the window args.'),
      parts: z.union([z.array(z.number().int().min(0)).min(1), z.literal('all')]).optional().describe('whole_song only: plan ONE project layout across SEVERAL parts at once. Pass the partIds from list_tracks, or "all" for every non-empty part. This is the difference between a part plan and a SONG plan: a song is a bass and a pad and a lead and drums, and if each were windowed on its own the projects would not line up musically. With `parts` the chop is computed ONCE (from the union of the parts\' section markers and their combined per-bar occupancy) and applied identically to all of them, so every part is cut at the same bars. Costs one fetch per part, so it is a few seconds for a full band. Read-only.'),
      fuzz: z.number().min(0).max(1).optional().describe('whole_song only: fuzzy-merge threshold (default 0.10), held on EVERY layer of a multi-part build. Higher folds near-identical grooves into one section, toward the 8 slots; 0 = exact dedup.'),
      drum_map: z.record(z.string(), z.union([z.string(), z.number()])).optional().describe('Per-tab percussion remap: source number to a neutral voice name ("clap") or a GM number (39). Use when warnings name non-GM numbers that were skipped, e.g. {"0": "clap"} for a tab that writes its clap layer on number 0. Judge what the number plays from where it lands (a number stacked with the snare on backbeats is usually the clap layer) and confirm by ear. Songsterr numbers 27-34 are its engraving-only effect block (High Q, Slap, Scratch Push/Pull, Sticks, Square Click, Metronome Click/Bell) and are reported unmapped rather than voiced; map one explicitly if a tab really plays it.'),
      ghost_velocity: z.number().int().min(1).max(127).optional().describe('How loud a GHOSTED hit sounds (default 40, against a plain hit of 100 and an accent of 120). A ghost note is a real hit played very quietly, the soft tail snare that makes a groove recognisable, so it is never dropped and there is no value that silences it. Raise it if the ghosts are inaudible on the target pads, lower it for a lighter touch.'),
      voice_name: z.string().optional().describe('MELODIC parts only: which key the returned pitch row is filed under in `voices`, i.e. which track of the target plays it. Default "synth1". Use the target\'s own voice names (Circuit Tracks: synth1 / synth2 / midi1 / midi2).'),
      transpose: z.number().int().min(-48).max(48).optional().describe('MELODIC parts only: semitones to shift the whole part, applied after pitch = tuning[string] + fret. Use -12 / +12 to bring a part into the target\'s playable range without editing the tab (After Dark\'s bass sits at d#1).'),
      note_lengths: z.boolean().optional().describe('MELODIC parts only: write each note\'s LENGTH and TIE into the returned pitch row as ":len" (steps) and "_" suffixes. DEFAULT TRUE, and leave it that way: a bare pitch row authors every note ONE STEP long whatever the tab holds, so a pad becomes a blip and the receipt still looks clean. What the 16-step gate ceiling cost is counted in `melodic.gate_splits` / `gate_clamps` / `ties_emitted`, and `melodic.cells` keeps each note\'s un-split source length. Set false only for a target with no note-length model, or when you are doing your own length pass from `melodic.cells`.'),
      articulations: z.boolean().optional().describe('MELODIC parts only: carry the source\'s ARTICULATIONS into real gate and velocity. DEFAULT TRUE, and leave it that way. Palm mute becomes a short gate plus a modest velocity trim, a per-note accent becomes a velocity BUMP on top of the sticky dynamic (not a replacement for it), let-ring sustains the note until its own pitch is struck again, and a hammer-on / pull-off or a slide WITH a written destination overlaps the next onset\'s gate so the target is not re-attacked. Every one is reported per cell in `melodic.cells[].articulations` and in aggregate in `melodic.articulation_applied`. Set false to get the written lengths and unarticulated velocity, e.g. to hear what the articulation is doing by comparison; the markings are then listed in `dropped_fidelity.parsed_not_authored`. Engraving-only fields, the ones never worth relaying as a loss, sit apart in `dropped_fidelity.not_a_loss`.'),
      palm_mute_gate_beats: z.number().min(0).max(4).optional().describe('MELODIC parts only: how long a PALM-MUTED note rings, in quarter beats. Default 0.125 (an eighth of a beat, ~69 ms at 108 bpm, a real muted-chug decay). In beats rather than steps so the same marking rings for the same real time at a 16th grid and a 32nd grid. Raise it if the chugs sound clipped on a slow-attack patch; 0 leaves palm-muted lengths alone and keeps only the velocity trim.'),
      palm_mute_velocity_scale: z.number().min(0.1).max(1).optional().describe('MELODIC parts only: the velocity multiplier on a PALM-MUTED note. Default 0.85, deliberately modest. A palm mute is shorter AND darker; only the shorter half fits in a note, and on most synth patches velocity reaches the filter as well as the amp, so a small trim buys some of the darkness. Kept small on purpose: on a patch that routes velocity to the amp alone, a big drop would turn the riff quiet, which is worse than a riff that is merely not dark enough. 1 disables the velocity half and keeps only the short gate.'),
      let_ring_max_beats: z.number().min(0).max(16).optional().describe('MELODIC parts only: cap on a LET-RING extension, in quarter beats. Default 4 (one 4/4 bar). A let-ring note sustains until its own pitch is struck again; this bounds the case where that never happens, so one marked bass note does not ring for twenty bars. 0 disables let-ring entirely (notes author at their written length).'),
      legato_overlap_sixths: z.number().int().min(0).max(6).optional().describe('MELODIC parts only: how far, in sixths of a step, a LEGATO launch note holds PAST its target\'s onset so the two overlap and the target is not heard as a fresh attack. Default 2. Overlap, not a tie: a tie into a different pitch is refused on purpose, and overlapping gates are normal stored content (a 130-file factory census found 279 of them). 0 disables the legato connection, so hammer-ons and slides author as separate attacks.'),
    },
  }, async (args) => {
    try {
      return asText(await executeImportSongsterr(args));
    } catch (err) {
      return asError(err);
    }
  });
}
