/**
 * FM3 kind-classification guard (the FAMILY-JOIN corrected state).
 *
 * Owns: the FM3-side data the catalog boundary's kind-classification is gated
 * on — the family-join discrete-ordinal overlay (`FM3_FAMILY_JOIN_DISCRETE`,
 * generated by `scripts/generate-fm3-family-join-discrete.ts`).
 *
 * THIS IS THE PLANNED DELIBERATE REWRITE the previous suite header demanded.
 * The prior suite pinned the UNCORRECTED state (FM3 type/count selectors
 * routing continuous — the same latent wrong-value bug the FM9 fixed
 * 2026-06-18 via its own editor-cache enum data and the III fixed 2026-06-20
 * via the chihotta roundtrip oracle) and said any change must be a deliberate
 * rewrite. On 2026-07-02 the correction landed for the FM3 via FAMILY JOIN:
 * the gen-3 family shares one effect codec and symbol vocabulary, so a param's
 * discrete-vs-continuous kind is a property of the shared algorithm; FM3
 * catalog symbols are classified discrete when the FM9 cache (kind:'enum')
 * and/or the FM9/III hardware roundtrips classify the same (family, SYMBOL)
 * discrete. Join is by SYMBOL, never paramId (cookbook negative
 * gen3-paramid-reuse-across-model-bytes).
 *
 * EVIDENCE: family-pattern (STRONG per the shipping bar), community-beta.
 * ORACLE PENDING: an FM3 SET→GET roundtrip (queued for Drew's next FM3
 * session) is the hardware confirm; when it lands, regenerate against it with
 * `scripts/generate-gen3-roundtrip-discrete.ts` and rewrite this suite again
 * against the device's own data.
 */
import * as fm3 from '../../../src/gen3/fm3/index.js';
import {
  FM3_PARAMS,
  FM3_FAMILY_JOIN_DISCRETE,
  FM3_FAMILY_JOIN_PROVENANCE,
} from '../../../src/gen3/fm3/index.js';

function assert(cond: boolean, msg: string): void {
  if (!cond) throw new Error(msg);
}
function unitOf(family: string, name: string): string | undefined {
  return FM3_PARAMS.find((p) => p.family === family && p.name === name)?.unit;
}

const byName = new Map(FM3_PARAMS.map((p) => [p.name, p]));

const cases: Array<() => void> = [];

// ── Export surface (documented; a change here is a classification-story change) ─
cases.push(() => {
  const got = Object.keys(fm3).sort().join(',');
  const want = 'FM3_FAMILIES,FM3_FAMILY_JOIN_DISCRETE,FM3_FAMILY_JOIN_PROVENANCE,FM3_PARAMS,FM3_PARAMS_BY_FAMILY';
  assert(got === want, `FM3 export surface changed: ${got} (documented: ${want})`);
});
// A true FM3 oracle still does NOT exist: no roundtrip overlay, no cache
// ranges. When either lands, the family-join overlay must be superseded by a
// regeneration against the device's own data — rewrite this suite then.
cases.push(() => assert(!('FM3_ROUNDTRIP_DISCRETE' in fm3), 'FM3 now exports FM3_ROUNDTRIP_DISCRETE — a device-own roundtrip oracle landed; regenerate and rewrite this suite against it (supersede the family join)'));
cases.push(() => assert(!('FM3_RANGES' in fm3), 'FM3 now exports FM3_RANGES — device-cache ranges landed; rewrite this suite against them (supersede the family join)'));

// ── Overlay: derived invariants ─────────────────────────────────────────────
// Every overlay key must join to a real device-true FM3 catalog param — an
// orphan key means the catalog regen and the overlay drifted apart.
for (const name of Object.keys(FM3_FAMILY_JOIN_DISCRETE)) {
  cases.push(() => assert(byName.has(name), `FM3 overlay key ${name} not in FM3_PARAMS (catalog/overlay drift)`));
}
// Every overlay row carries a provenance, and vice versa (parallel tables).
cases.push(() => {
  const a = Object.keys(FM3_FAMILY_JOIN_DISCRETE).sort().join(',');
  const b = Object.keys(FM3_FAMILY_JOIN_PROVENANCE).sort().join(',');
  assert(a === b, 'FM3 overlay / provenance key sets diverged');
});
// Provenance values are the two documented sources only.
for (const [name, prov] of Object.entries(FM3_FAMILY_JOIN_PROVENANCE)) {
  cases.push(() =>
    assert(
      prov === 'fm9-cache-family-join' || prov === 'sibling-roundtrip-family-join',
      `FM3 overlay ${name} has unknown provenance "${prov}"`,
    ),
  );
}
// Every bound is a positive integer <= 1024 (the roundtrip selection bound;
// the FM9 cache enum counts also stay within it).
for (const [name, ord] of Object.entries(FM3_FAMILY_JOIN_DISCRETE)) {
  cases.push(() => assert(Number.isInteger(ord) && ord >= 1 && ord <= 1024, `FM3 overlay ${name}=${ord} out of [1..1024]`));
}
// Regenerating from the same sibling evidence is deterministic: 473 entries
// (436 fm9-cache-family-join + 37 sibling-roundtrip-family-join).
cases.push(() =>
  assert(
    Object.keys(FM3_FAMILY_JOIN_DISCRETE).length === 473,
    `FM3 overlay size ${Object.keys(FM3_FAMILY_JOIN_DISCRETE).length} != 473 (regen from the sibling evidence must reproduce exactly 473)`,
  ),
);
cases.push(() => {
  let cache = 0;
  let rt = 0;
  for (const prov of Object.values(FM3_FAMILY_JOIN_PROVENANCE)) {
    if (prov === 'fm9-cache-family-join') cache += 1;
    else rt += 1;
  }
  assert(cache === 436 && rt === 37, `FM3 overlay provenance split ${cache}/${rt} != 436/37`);
});

// ── Discrete direction: XML-overlay enums still route discrete ──────────────
// (unchanged by the family join — these already had enum vocabularies).
cases.push(() => assert(unitOf('REVERB', 'REVERB_TYPE') === 'enum', `FM3 REVERB_TYPE unit ${unitOf('REVERB', 'REVERB_TYPE')} (documented 'enum' — must route discrete)`));
cases.push(() => assert(unitOf('DISTORT', 'DISTORT_TYPE') === 'enum', `FM3 DISTORT_TYPE unit ${unitOf('DISTORT', 'DISTORT_TYPE')} (documented 'enum' — amp model selector must route discrete)`));
// ...and therefore must NOT be in the overlay (it covers exactly what the
// existing enum paths miss — mirrors the FM9 no-overlap invariant).
cases.push(() => assert(FM3_FAMILY_JOIN_DISCRETE['REVERB_TYPE'] === undefined, 'FM3 overlay must EXCLUDE REVERB_TYPE (already discrete via the enum vocab)'));
cases.push(() => assert(FM3_FAMILY_JOIN_DISCRETE['DISTORT_TYPE'] === undefined, 'FM3 overlay must EXCLUDE DISTORT_TYPE (already discrete via the enum vocab)'));

// ── The CORRECTED class: family-joined selectors now route discrete ─────────
// On the FM9/III the 2026-06-18 roundtrip proved CABINET_TYPE1 and
// CHORUS_VOICES are device-quantized ordinals; the FM3 catalog documented them
// with continuous-ish units ('numeric' / 'count' — pinned by the previous
// suite). The family join now routes them DISCRETE. The catalog unit tags are
// unchanged (the correction is the overlay, not a catalog regen); the bound is
// the LARGEST sibling ordinal (III CABINET_TYPE1=188 > FM9=15; devices clamp
// over-range ordinals, an under-bound would refuse valid ones).
cases.push(() => assert(unitOf('CABINET', 'CABINET_TYPE1') === 'numeric', `FM3 CABINET_TYPE1 catalog unit ${unitOf('CABINET', 'CABINET_TYPE1')} (still 'numeric' — the overlay, not a regen, flips the routing)`));
cases.push(() => assert(FM3_FAMILY_JOIN_DISCRETE['CABINET_TYPE1'] === 188, `FM3 CABINET_TYPE1 overlay ordinal = ${FM3_FAMILY_JOIN_DISCRETE['CABINET_TYPE1']} (want 188 = max(III 188, FM9 15))`));
cases.push(() => assert(FM3_FAMILY_JOIN_PROVENANCE['CABINET_TYPE1'] === 'sibling-roundtrip-family-join', `FM3 CABINET_TYPE1 provenance ${FM3_FAMILY_JOIN_PROVENANCE['CABINET_TYPE1']}`));
cases.push(() => assert(unitOf('CHORUS', 'CHORUS_VOICES') === 'count', `FM3 CHORUS_VOICES catalog unit ${unitOf('CHORUS', 'CHORUS_VOICES')} (still 'count' — the overlay flips the routing)`));
cases.push(() => assert(FM3_FAMILY_JOIN_DISCRETE['CHORUS_VOICES'] === 4, `FM3 CHORUS_VOICES overlay ordinal = ${FM3_FAMILY_JOIN_DISCRETE['CHORUS_VOICES']} (want 4)`));
// A headline fm9-cache-family-join anchor: the delay model selector (the FM9
// cache marks DELAY_MODEL enum/29; the III roundtrip agrees at 28 = 29-1).
cases.push(() => assert(FM3_FAMILY_JOIN_DISCRETE['DELAY_MODEL'] === 28, `FM3 DELAY_MODEL overlay ordinal = ${FM3_FAMILY_JOIN_DISCRETE['DELAY_MODEL']} (want 28)`));
cases.push(() => assert(FM3_FAMILY_JOIN_PROVENANCE['DELAY_MODEL'] === 'fm9-cache-family-join', `FM3 DELAY_MODEL provenance ${FM3_FAMILY_JOIN_PROVENANCE['DELAY_MODEL']}`));

// ── Continuous direction: true knobs stay continuous ────────────────────────
cases.push(() => assert(unitOf('REVERB', 'REVERB_TIME') === 'seconds', `FM3 REVERB_TIME unit ${unitOf('REVERB', 'REVERB_TIME')} (documented 'seconds' — continuous knob)`));
for (const name of ['REVERB_TIME', 'REVERB_MIX', 'DISTORT_DRIVE', 'DISTORT_MASTER']) {
  cases.push(() => assert(FM3_FAMILY_JOIN_DISCRETE[name] === undefined, `FM3 ${name} must NOT be in the family-join overlay (continuous knob)`));
}

// ── Incident-magnitude floor ────────────────────────────────────────────────
// The FM9 correction was ~351 params, the III ~92; the FM3 shares most of the
// FM9's symbol space, so a healthy family join lands in the hundreds. A regen
// collapsing below 351 means the joined discrete class collapsed — fail.
cases.push(() =>
  assert(
    Object.keys(FM3_FAMILY_JOIN_DISCRETE).length >= 351,
    `FM3 family-join size ${Object.keys(FM3_FAMILY_JOIN_DISCRETE).length} < 351 (the corrected class collapsed)`,
  ),
);

export function runFm3KindClassificationTests(): void {
  for (const c of cases) c();
}
export const FM3_KIND_CLASSIFICATION_CASE_COUNT = cases.length;
