/**
 * Transfer-candidates report generator (Gate 4 of the RE-workflow gates).
 *
 * Parses the cookbook INDEX table (Primitive / Class / Status / Devices
 * columns) and, for every POSITIVE entry (`matched` / `matched-singleton`),
 * computes which family members the primitive has NOT been verified on.
 * A candidate = a primitive verified on >= 1 member of a family group and
 * missing >= 1 other member. Family groups are deliberately simple and
 * explicit (see FAMILY_GROUPS); the Devices column is free text, so tokens
 * are normalized and unknown tokens cause the row to be skipped WITH a note
 * rather than guessed at.
 *
 * Output: packages/fractal-midi/docs/research/transfer-candidates.generated.md
 * — a curiosity-surfacing report (see its header), regenerated by running
 * this script. `scripts/verify-re-ledger.ts` regenerates it in memory and
 * FAILS on drift against the committed file (the catalog:check pattern), so
 * coverage changes force a regen commit. The output is deterministic (no
 * timestamps) so a second run produces no diff.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MCP_ROOT = path.resolve(HERE, '..');
const RESEARCH_ROOT = path.join(MCP_ROOT, 'packages', 'fractal-midi', 'docs', 'research');
const COOKBOOK_INDEX = path.join(RESEARCH_ROOT, 'cookbook', 'INDEX.md');
export const REPORT_PATH = path.join(RESEARCH_ROOT, 'transfer-candidates.generated.md');

/**
 * Canonical device tokens. GEN3 is a derived macro-member of the
 * Fractal-wide group: it counts as present when ANY gen-3 device
 * (III / FM3 / FM9 / VP4) is verified.
 */
const GEN3_DEVICES = new Set(['III', 'FM3', 'FM9', 'VP4']);
const KNOWN_TOKENS: Record<string, string> = {
  am4: 'AM4',
  ii: 'II',
  iii: 'III',
  fm3: 'FM3',
  fm9: 'FM9',
  vp4: 'VP4',
  gen1: 'GEN1',
  hydra: 'HYDRA', // known, but belongs to no Fractal family group
};

/** Keep the family mapping SIMPLE and explicit. */
const FAMILY_GROUPS: { name: string; members: string[] }[] = [
  { name: 'gen-3', members: ['III', 'FM3', 'FM9', 'VP4'] },
  { name: 'Fractal-wide', members: ['AM4', 'II', 'GEN3', 'GEN1'] },
];

const DISPLAY: Record<string, string> = {
  AM4: 'AM4', II: 'II', III: 'III', FM3: 'FM3', FM9: 'FM9', VP4: 'VP4',
  GEN1: 'gen-1 (Standard/Ultra)', GEN3: 'gen-3 (III/FM3/FM9/VP4)', HYDRA: 'Hydra',
};

interface IndexRow { primitive: string; status: string; devicesRaw: string; }

function parseIndexRows(indexSource: string): IndexRow[] {
  const rows: IndexRow[] = [];
  for (const line of indexSource.split(/\r?\n/)) {
    const m = line.match(/^\|\s*\[([^\]]+)\]\([^)]+\)\s*\|[^|]*\|([^|]*)\|([^|]*)\|/);
    if (!m) continue;
    rows.push({ primitive: m[1].trim(), status: m[2].trim(), devicesRaw: m[3].trim() });
  }
  return rows;
}

/** Normalize the free-text Devices column into canonical tokens. */
function parseDeviceTokens(raw: string): { devices: string[]; unknown: string[] } {
  let s = raw;
  // The one free-text form containing a '/' inside a single device name.
  s = s.replace(/Standard\/Ultra\s*\(gen-1\)/gi, 'gen1');
  s = s.replace(/\([^)]*\)/g, ' '); // strip parentheticals: "II (Q8 + Q9)" -> "II"
  const devices: string[] = [];
  const unknown: string[] = [];
  for (const tokRaw of s.split(/[/,+]/)) {
    const tok = tokRaw.trim();
    if (tok === '') continue;
    const canon = KNOWN_TOKENS[tok.toLowerCase().replace(/[^a-z0-9]/g, '')];
    if (canon === undefined) unknown.push(tok);
    else if (!devices.includes(canon)) devices.push(canon);
  }
  return { devices, unknown };
}

function candidateGaps(devices: string[]): { verified: string[]; missing: string[] } | null {
  const present = new Set(devices);
  if ([...GEN3_DEVICES].some((d) => present.has(d))) present.add('GEN3');
  const missing: string[] = [];
  let anyGroupHit = false;
  for (const group of FAMILY_GROUPS) {
    const has = group.members.filter((m) => present.has(m));
    const lacks = group.members.filter((m) => !present.has(m));
    if (has.length >= 1 && lacks.length >= 1) {
      anyGroupHit = true;
      for (const m of lacks) if (!missing.includes(m)) missing.push(m);
    }
  }
  if (!anyGroupHit) return null;
  return { verified: devices, missing };
}

export function generateReport(): string {
  if (!existsSync(COOKBOOK_INDEX)) {
    throw new Error(`cookbook INDEX not found: ${COOKBOOK_INDEX}`);
  }
  const rows = parseIndexRows(readFileSync(COOKBOOK_INDEX, 'utf8'));
  const crossFamily: string[] = [];
  const singletons: string[] = [];
  const skipped: string[] = [];
  let positives = 0;
  for (const row of rows) {
    if (row.status !== 'matched' && row.status !== 'matched-singleton') continue;
    positives += 1;
    const { devices, unknown } = parseDeviceTokens(row.devicesRaw);
    if (unknown.length > 0) {
      skipped.push(`- ${row.primitive}: unrecognized device token(s) ${unknown.map((u) => `'${u}'`).join(', ')} in Devices column '${row.devicesRaw}'`);
      continue;
    }
    const gaps = candidateGaps(devices);
    if (gaps === null) continue;
    const line =
      `- **${row.primitive}**: verified ${gaps.verified.map((d) => DISPLAY[d]).join(' / ')}; ` +
      `untested on ${gaps.missing.map((d) => DISPLAY[d]).join(' / ')} — transfer hypothesis per RE-WORKFLOW cross-device reflex`;
    (row.status === 'matched' ? crossFamily : singletons).push(line);
  }
  const lines: string[] = [
    '# Transfer candidates (GENERATED — do not hand-edit)',
    '',
    '> Generated by `scripts/gen-transfer-candidates.ts` from the cookbook',
    '> INDEX table. `scripts/verify-re-ledger.ts` fails on drift against this',
    '> file, so re-run the generator after any cookbook coverage change.',
    '>',
    '> This is a **curiosity-surfacing report, not a compliance list**: each',
    '> line is a cheap transfer HYPOTHESIS (a primitive proven on one family',
    '> member and never checked on a sibling), per the RE-WORKFLOW cross-device',
    '> transfer reflex. Some gaps are real opportunities; others have no second',
    '> axis by construction (especially in the Singletons section, where the',
    '> entry body may already explain why no sibling applies). Judge each',
    '> against the entry body before spending a session on it.',
    '',
    `Family groups: gen-3 = {III, FM3, FM9, VP4}; Fractal-wide = {AM4, II, gen-3, gen-1}.`,
    `Positive entries scanned: ${positives}.`,
    '',
    '## Cross-family gaps (status: matched)',
    '',
    ...(crossFamily.length > 0 ? crossFamily : ['(none)']),
    '',
    '## Singletons (status: matched-singleton — the entry body may already rule out a second axis)',
    '',
    ...(singletons.length > 0 ? singletons : ['(none)']),
    '',
    '## Skipped rows (unparseable Devices column — fix the INDEX or extend the token map)',
    '',
    ...(skipped.length > 0 ? skipped : ['(none)']),
    '',
  ];
  return lines.join('\n');
}

function main(): void {
  const report = generateReport();
  const prior = existsSync(REPORT_PATH) ? readFileSync(REPORT_PATH, 'utf8') : null;
  if (prior === report) {
    console.log(`gen-transfer-candidates: no change (${REPORT_PATH}).`);
    return;
  }
  writeFileSync(REPORT_PATH, report, 'utf8');
  console.log(`gen-transfer-candidates: wrote ${REPORT_PATH} (${report.split('\n').length} lines).`);
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  main();
}
