/**
 * Tool inventory generator (T-1).
 *
 * Spawns the built MCP server with MCP_TOOLS_PROFILE=full, asks it
 * for every registered tool via `tools/list`, partitions the result
 * into core / experimental / full profiles using the same set logic
 * the server uses at boot, and writes the inventory to docs/TOOLS.md.
 *
 * Also updates the high-level tool-count summary in README.md inside
 * an HTML-comment-fenced region so preflight can detect drift.
 *
 * Run:
 *   npm run tools:inventory                # write docs/TOOLS.md + README region
 *   npm run tools:inventory -- --check     # exit non-zero on drift
 *
 * Exit codes:
 *   0 — files written (write mode) or no drift detected (check mode)
 *   1 — drift detected in check mode, or generator failed
 *   2 — MCP server failed to start
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';

import {
  CORE_TOOLS,
  EXPERIMENTAL_EXCLUDED,
} from '../packages/server-all/dist/server/toolProfiles.js';

const REPO_ROOT = process.cwd();
const SERVER_ENTRY = path.resolve(REPO_ROOT, 'packages', 'server-all', 'dist', 'server', 'index.js');
const README_PATH = path.resolve(REPO_ROOT, 'README.md');
const TOOLS_MD_PATH = path.resolve(REPO_ROOT, 'docs', 'TOOLS.md');

const README_REGION_START = '<!-- tool-inventory:generated:start -->';
const README_REGION_END = '<!-- tool-inventory:generated:end -->';

const DESCRIPTION_WARN_CHARS = 600;
const DESCRIPTION_HARD_CAP_CHARS = 1000;

interface ToolEntry {
  name: string;
  description: string;
  charCount: number;
}

interface ProfileBucket {
  name: 'core' | 'experimental' | 'full';
  description: string;
  tools: ToolEntry[];
}

async function listAllTools(): Promise<ToolEntry[]> {
  const transport = new StdioClientTransport({
    command: process.execPath,
    args: [SERVER_ENTRY],
    env: { ...process.env, MCP_TOOLS_PROFILE: 'full' },
    stderr: 'pipe',
  });
  // Silence the server's startup banner; we don't need it cluttering our output.
  if (transport.stderr) transport.stderr.on('data', () => {});
  const client = new Client({ name: 'tool-inventory', version: '1.0.0' }, { capabilities: {} });
  try {
    await client.connect(transport);
  } catch (err) {
    console.error(`Failed to connect to MCP server at ${SERVER_ENTRY}:`, err);
    console.error('Did you run `npm run build`?');
    process.exit(2);
  }
  const listed = await client.listTools();
  const entries: ToolEntry[] = (listed.tools ?? []).map((t) => {
    const description = typeof t.description === 'string' ? t.description : '';
    return { name: t.name, description, charCount: description.length };
  });
  entries.sort((a, b) => a.name.localeCompare(b.name));
  await client.close();
  return entries;
}

function bucketByProfile(all: ToolEntry[]): ProfileBucket[] {
  const core = all.filter((t) => CORE_TOOLS.has(t.name));
  const experimental = all.filter((t) => !EXPERIMENTAL_EXCLUDED.has(t.name));
  return [
    {
      name: 'core',
      description:
        'Default-recommended unified surface for conversational tone-building. Smallest agent context. Set `MCP_TOOLS_PROFILE=core` to select.',
      tools: core,
    },
    {
      name: 'experimental',
      description:
        'Core + every device-namespaced tool + raw generic-MIDI primitives + diagnostics. Used during dev when poking hardware-specific capabilities. Set `MCP_TOOLS_PROFILE=experimental` to select.',
      tools: experimental,
    },
    {
      name: 'full',
      description:
        'Everything registered (current default; equivalent to no env var). Preserved as the v0.1 baseline so upgrades do not lose tools.',
      tools: all,
    },
  ];
}

function firstSentence(text: string): string {
  if (text.length === 0) return '';
  const trimmed = text.replace(/\s+/g, ' ').trim();
  const dotIdx = trimmed.indexOf('. ');
  const candidate = dotIdx === -1 ? trimmed : trimmed.slice(0, dotIdx + 1);
  return candidate.length > 160 ? candidate.slice(0, 157) + '...' : candidate;
}

function renderToolsMd(buckets: ProfileBucket[], all: ToolEntry[]): string {
  const lines: string[] = [];
  lines.push('# MCP Tool Inventory');
  lines.push('');
  lines.push('<!-- generated by scripts/list-tools.ts; do not edit by hand -->');
  lines.push('<!-- regenerate with `npm run tools:inventory`; preflight enforces sync via tools:inventory-check -->');
  lines.push('');
  lines.push(`**Total registered tools:** ${all.length}.`);
  lines.push('');
  lines.push('The server exposes three tool profiles selected at boot via the `MCP_TOOLS_PROFILE` env var (set in your `claude_desktop_config.json`). Tools listed under a profile appear in `tools/list` when that profile is active; tools excluded from a profile are not registered at all (no token cost in the agent context).');
  lines.push('');
  lines.push('See [README.md § Configuring tool profiles](../README.md#configuring-tool-profiles) for setup. To resurrect a tool that has been permanently removed (rather than profile-hidden), see [TOOL-ARCHIVE.md](TOOL-ARCHIVE.md).');
  lines.push('');
  lines.push('## Profile counts');
  lines.push('');
  lines.push('| Profile | Tool count | Average description length | Tools over 600 chars | Tools over 1000 chars |');
  lines.push('|---|---|---|---|---|');
  for (const b of buckets) {
    const total = b.tools.length;
    const avg = total === 0 ? 0 : Math.round(b.tools.reduce((s, t) => s + t.charCount, 0) / total);
    const over600 = b.tools.filter((t) => t.charCount > DESCRIPTION_WARN_CHARS).length;
    const over1000 = b.tools.filter((t) => t.charCount > DESCRIPTION_HARD_CAP_CHARS).length;
    lines.push(`| \`${b.name}\` | ${total} | ${avg} chars | ${over600} | ${over1000} |`);
  }
  lines.push('');
  for (const b of buckets) {
    lines.push(`## ${b.name} profile (${b.tools.length} tools)`);
    lines.push('');
    lines.push(b.description);
    lines.push('');
    lines.push('| Tool | Description length | First sentence |');
    lines.push('|---|---|---|');
    for (const t of b.tools) {
      const flag = t.charCount > DESCRIPTION_HARD_CAP_CHARS
        ? ` ⚠️ over ${DESCRIPTION_HARD_CAP_CHARS}`
        : t.charCount > DESCRIPTION_WARN_CHARS
          ? ` ⚠`
          : '';
      const sentence = firstSentence(t.description).replace(/\|/g, '\\|');
      lines.push(`| \`${t.name}\` | ${t.charCount}${flag} | ${sentence} |`);
    }
    lines.push('');
  }
  lines.push('## Description budget outliers');
  lines.push('');
  lines.push(`Tools with descriptions over ${DESCRIPTION_HARD_CAP_CHARS} chars. T-4 / T-13 target these for migration into structured response fields.`);
  lines.push('');
  const outliers = all
    .filter((t) => t.charCount > DESCRIPTION_HARD_CAP_CHARS)
    .sort((a, b) => b.charCount - a.charCount);
  if (outliers.length === 0) {
    lines.push('_None._');
  } else {
    lines.push('| Tool | Description length |');
    lines.push('|---|---|');
    for (const t of outliers) {
      lines.push(`| \`${t.name}\` | ${t.charCount} chars |`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

function renderReadmeRegion(buckets: ProfileBucket[], all: ToolEntry[]): string {
  const lines: string[] = [];
  lines.push(README_REGION_START);
  lines.push('');
  lines.push(`**${all.length} MCP tools registered across 3 profiles.** Defaults to \`full\` so upgrades preserve every tool; set \`MCP_TOOLS_PROFILE\` in \`claude_desktop_config.json\` env to opt into the smaller surfaces.`);
  lines.push('');
  lines.push('| Profile | Tool count | When to use |');
  lines.push('|---|---|---|');
  for (const b of buckets) {
    const when = b.name === 'core'
      ? 'Default-recommended: smallest agent context, unified surface only.'
      : b.name === 'experimental'
        ? 'Dev / diagnostic surface: every device-namespaced tool + raw MIDI primitives.'
        : 'Compatibility baseline; preserves every registered tool.';
    lines.push(`| \`${b.name}\` | ${b.tools.length} | ${when} |`);
  }
  lines.push('');
  lines.push('Full per-profile tool list with description-length stats: [`docs/TOOLS.md`](docs/TOOLS.md). Generated by `npm run tools:inventory`; preflight checks for drift.');
  lines.push('');
  lines.push(README_REGION_END);
  return lines.join('\n');
}

function spliceReadmeRegion(readme: string, region: string): { updated: string; existed: boolean } {
  const startIdx = readme.indexOf(README_REGION_START);
  const endIdx = readme.indexOf(README_REGION_END);
  if (startIdx === -1 || endIdx === -1) {
    return { updated: readme, existed: false };
  }
  const before = readme.slice(0, startIdx);
  const after = readme.slice(endIdx + README_REGION_END.length);
  return { updated: before + region + after, existed: true };
}

async function main(): Promise<void> {
  const checkMode = process.argv.includes('--check');
  const all = await listAllTools();
  const buckets = bucketByProfile(all);
  const toolsMd = renderToolsMd(buckets, all);
  const readmeRegion = renderReadmeRegion(buckets, all);
  const readme = readFileSync(README_PATH, 'utf8');
  const { updated: newReadme, existed } = spliceReadmeRegion(readme, readmeRegion);

  if (checkMode) {
    let drift = false;
    const currentTools = (() => {
      try { return readFileSync(TOOLS_MD_PATH, 'utf8'); } catch { return ''; }
    })();
    if (currentTools !== toolsMd) {
      console.error(`Drift: docs/TOOLS.md is out of sync. Run npm run tools:inventory.`);
      drift = true;
    }
    if (!existed) {
      console.error(`Drift: README.md is missing the generated region markers. Run npm run tools:inventory.`);
      drift = true;
    } else if (newReadme !== readme) {
      console.error(`Drift: README.md's tool-inventory region is out of sync. Run npm run tools:inventory.`);
      drift = true;
    }
    if (drift) process.exit(1);
    console.log(`No drift: docs/TOOLS.md and README.md are up to date (${all.length} tools).`);
    return;
  }

  writeFileSync(TOOLS_MD_PATH, toolsMd, 'utf8');
  console.log(`Wrote docs/TOOLS.md (${all.length} tools across ${buckets.length} profiles).`);
  if (existed) {
    if (newReadme !== readme) {
      writeFileSync(README_PATH, newReadme, 'utf8');
      console.log(`Updated README.md tool-inventory region.`);
    } else {
      console.log(`README.md tool-inventory region is already up to date.`);
    }
  } else {
    console.error(`README.md is missing the region markers; add this block where you want the auto-generated summary:\n${readmeRegion}\n`);
  }
}

main().catch((err) => {
  console.error('tool-inventory generator failed:', err);
  process.exit(1);
});
