/**
 * Generate a gen-3 roundtrip-derived discrete-ordinal overlay from a
 * `gen3-full-roundtrip` oracle JSON.
 *
 * THE PROBLEM. A type/model/mode selector or integer-count param that the
 * device treats as an ORDINAL must be SET as a discrete float32(ordinal)
 * (sub 09 00). Sent CONTINUOUS (the catalog's default for any param the
 * editor-cache / AM4 / XML overlay missed), the device QUANTIZES the
 * normalized float to the nearest ordinal and stores the WRONG value. The
 * FM9 enum-flow fix corrected the params the editor cache marked enum; this
 * overlay extends the same correction to the params that path MISSED, using
 * the device's OWN roundtrip behaviour as the discriminator.
 *
 * THE ORACLE. A full hardware roundtrip sweep (probe `gen3-full-roundtrip`):
 * for each param it SET a series of `sentWire` values and READ back the
 * `gotWire` the device stored. A discrete selector sent continuous shows
 * `gotWire` quantized to a small int (REVERB_TYPE: sentWire 65534 -> gotWire
 * 78 = enumCount-1); a TRUE continuous param passes through (gotWire ~=
 * sentWire ~= 65534).
 *
 * THE SELECTION RULE (conservative — a false positive breaks that param's
 * writes). A param qualifies as roundtrip-discrete iff, across its `values`
 * sweep:
 *   1. every `gotWire` is a non-negative integer, AND
 *   2. `gotWire` is monotonic non-decreasing as `sentWire` increases, AND
 *   3. at the max sentWire (65534), gotWire <= 1024 AND gotWire < sentWire
 *      (clearly quantized to a small ordinal, NOT pass-through), AND
 *   4. the max gotWire is >= 1 (skip all-zero / unresponsive params).
 * `maxOrdinal = gotWire at the max sentWire`. The gotWire-quantization signal
 * IS the discriminator; rule 3 is what protects true continuous params. There
 * is deliberately NO name-pattern filter.
 *
 * Usage:  tsx scripts/generate-gen3-roundtrip-discrete.ts <roundtrip.json> [--const NAME]
 * Prints a sorted `{name: maxOrdinal}` TS module to stdout. Deterministic and
 * idempotent (keys sorted).
 */
import { readFileSync } from 'node:fs';

interface SweepValue {
  pct: number;
  sentWire: number;
  gotWire: number;
  pass: boolean;
}
interface OracleParam {
  family: string;
  paramId: number;
  name: string;
  kind: string;
  values?: SweepValue[];
}
interface OracleFamily {
  family: string;
  effectId: number;
  placed: boolean;
  params: OracleParam[];
}
interface Oracle {
  probe: string;
  device: string;
  modelByte: number;
  families: OracleFamily[];
}

const MAX_SENT = 65534;

/**
 * Apply the selection rule to one param's sweep. Returns the maxOrdinal when
 * the param qualifies as roundtrip-discrete, else undefined.
 */
export function roundtripDiscreteOrdinal(values: readonly SweepValue[]): number | undefined {
  if (values.length === 0) return undefined;

  // 1. every gotWire is a non-negative integer.
  for (const v of values) {
    if (!Number.isInteger(v.gotWire) || v.gotWire < 0) return undefined;
  }

  // 2. gotWire monotonic non-decreasing as sentWire increases.
  const sorted = [...values].sort((a, b) => a.sentWire - b.sentWire);
  for (let i = 1; i < sorted.length; i++) {
    if (sorted[i].gotWire < sorted[i - 1].gotWire) return undefined;
  }

  // Locate the sample at the max sentWire (the sweep's top, normally 65534).
  const top = sorted[sorted.length - 1];
  if (top.sentWire !== MAX_SENT) return undefined; // need the pass-through anchor
  const maxOrdinal = top.gotWire;

  // 3. clearly quantized at the top (small ordinal, NOT pass-through).
  if (!(maxOrdinal <= 1024 && maxOrdinal < top.sentWire)) return undefined;

  // 4. responsive (not stuck at zero).
  if (maxOrdinal < 1) return undefined;

  return maxOrdinal;
}

function build(oracle: Oracle): Record<string, number> {
  const out: Record<string, number> = {};
  for (const fam of oracle.families) {
    for (const p of fam.params) {
      const maxOrdinal = roundtripDiscreteOrdinal(p.values ?? []);
      if (maxOrdinal === undefined) continue;
      // First-wins on a duplicate name (paramIds are unique within a family but
      // a name could theoretically appear twice across families; keep the
      // lowest-ordinal deterministic answer).
      if (out[p.name] === undefined || maxOrdinal < out[p.name]) {
        out[p.name] = maxOrdinal;
      }
    }
  }
  return out;
}

function emit(oracle: Oracle, constName: string, jsonPath: string): string {
  const table = build(oracle);
  const keys = Object.keys(table).sort();
  const lines = keys.map((k) => `  ${JSON.stringify(k)}: ${table[k]},`);
  return [
    `// GENERATED by scripts/generate-gen3-roundtrip-discrete.ts — do not hand-edit.`,
    `// Oracle: ${jsonPath} (probe "${oracle.probe}", device "${oracle.device}",`,
    `// modelByte 0x${oracle.modelByte.toString(16)}), full hardware roundtrip sweep.`,
    `// Selection rule: a param is roundtrip-DISCRETE iff across its SET->READ sweep`,
    `// every gotWire is a non-negative integer, gotWire is monotonic non-decreasing`,
    `// in sentWire, and at the max sentWire (65534) gotWire <= 1024 AND < sentWire`,
    `// (clearly quantized to a small ordinal, not pass-through) AND max gotWire >= 1.`,
    `// maxOrdinal = gotWire at the max sentWire. Re-run the script to regenerate.`,
    `//`,
    `// These params are routed DISCRETE (float32(ordinal), sub 09 00) instead of`,
    `// CONTINUOUS — the wire builder is unchanged; only the catalog kind-classification`,
    `// differs, so the gen-3 byte-identity anchor stays intact.`,
    `/* eslint-disable */`,
    ``,
    `export const ${constName}: Readonly<Record<string, number>> = {`,
    ...lines,
    `};`,
    ``,
  ].join('\n');
}

function main(): void {
  const args = process.argv.slice(2);
  const constIdx = args.indexOf('--const');
  const constName = constIdx >= 0 ? args[constIdx + 1] : 'ROUNDTRIP_DISCRETE';
  const positional = args.filter((a, i) => a !== '--const' && args[i - 1] !== '--const');
  const jsonPath = positional[0];
  if (jsonPath === undefined) {
    console.error('usage: tsx generate-gen3-roundtrip-discrete.ts <roundtrip.json> [--const NAME]');
    process.exit(2);
  }
  const oracle = JSON.parse(readFileSync(jsonPath, 'utf8')) as Oracle;
  if (oracle.probe !== 'gen3-full-roundtrip') {
    console.error(`expected probe "gen3-full-roundtrip", got "${oracle.probe}"`);
    process.exit(2);
  }
  process.stdout.write(emit(oracle, constName, jsonPath));
}

// Run only when invoked directly (allows importing roundtripDiscreteOrdinal in tests).
if (import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith('generate-gen3-roundtrip-discrete.ts')) {
  main();
}
